### ISSUE TITLE
Read filtering fails

### ISSUE THREAD

**Issue by mjsull** [fxia22/HINGE#46]
Hi I get the following error when running Reads_filter

```
Reads_filter --db staph --las staph.las -x staph --config ../../utils/nominal.ini                                                                                                                                            (master) 
[2016-07-08 18:03:07.669] [log] [info] Reads filtering
terminate called after throwing an instance of 'spdlog::spdlog_ex'
  what():  formatting error while processing format string 'current user {}, current working directory {}': string pointer is null
```

**Comment by govinda-kamath** [comment]
Hi,

You should make run 

`mkdir log `

before running Reads_filter. I'm sorry we did not include it in the README. I've added it now. 

Govinda.

**Comment by mjsull** [comment]
Hi Govinda,

I ran into that error too, but managed to fix it myself. (also you point the script to an absolute directory /utils/nominal.ini not sure if that is intentional, I changed to ../../utils/nominal.ini).

This seems to be unrelated.

Thanks for the quick response,

Mitch

**Comment by govinda-kamath** [comment]
You're right, Mitch. It should not be an absolute path. It depends upon where the data is relative to nominal.ini. I've fixed it in the README. 

Thanks a ton,
Govinda.

**Comment by mjsull** [comment]
Hi Govinda,

Sorry I wasn't clear, the nominal.ini was independent of the problem I am having, just thought you might want to fix it in the readme.

Cheers,

Mitch

**Comment by govinda-kamath** [comment]
Yes. We really appreciate that. 

Thanks,

Govinda.

**Comment by mjsull** [comment]
Hi, sorry went away for the weekend.

> Reads_filter --db staph --las staph.las -x staph --config ../../utils/nominal.ini                                                                                                                                            (master) 
[2016-07-08 18:03:07.669] [log] [info] Reads filtering
terminate called after throwing an instance of 'spdlog::spdlog_ex'
  what():  formatting error while processing format string 'current user {}, current working directory {}': string pointer is null

This is the error I'm getting, mkdir log doesn't fix this problem.

Cheers,

Mitch

**Comment by govinda-kamath** [comment]
I see. I've seen this error before, but it usually indicated that there was no log sub-directory in the directory containing the DB and the las. 

 @fxia22 Any ideas?

**Comment by mjsull** [comment]
This is the error I get if there is no log directory

> Reads_filter --db staph --las staph.las -x staph --config ../../utils/nominal.ini
terminate called after throwing an instance of 'spdlog::spdlog_ex'
  what():  Failed opening file log/log_2016-07-11_16-35.txt for writing
[1]    9416 abort (core dumped)  Reads_filter --db staph --las staph.las -x staph --config

**Comment by fxia22** [comment]
@mjsull It seems `getlogin() or getwd()` does not work on your system, you can comment line 249 in `filter.cpp`. Also, you may need to comment other lines where `getlogin` or `getwd` presents. 

```
console->info("current user {}, current working directory {}", getlogin(), buff);
```

Sorry about the inconvenience.

**Comment by govinda-kamath** [comment]
We've made the line there just to work when the code is run in debug mode. On updating the repo, things should work for you as is. Let us know if this does not work or there are any other problems.

Thanks,
Govinda.

**Comment by mjsull** [comment]
Working now, thanks!
